language: bash

services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
    cd docker/ ;
    docker build --no-cache -t somrc/demo:latest . || exit 1;
    docker push somrc/demo:latest || exit 1;
    aws sqs send-message --queue-url 'https://sqs.us-east-1.amazonaws.com/474683445819/ithriv-updates' --message-body $TRAVIS_BRANCH || exit 1;

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - nmagee@virginia.edu
